#ifndef SRC_MAIN_H_
#define SRC_MAIN_H_

#include "xstatus.h"
#include "xparameters.h"

#define BRAM_WRITE_BASE_ADDRESS XPAR_AXI_BRAM_CTRL_0_S_AXI_BASEADDR
#define BRAM_READ_BASE_ADDRESS  XPAR_AXI_BRAM_CTRL_0_S_AXI_BASEADDR + 4*(0x800)

#define I2C_DEVICE_BASE_ADDR	XPAR_IIC_0_BASEADDR


#define CLK_DIV_BAUD_DBG 	((u32*) (BRAM_WRITE_BASE_ADDRESS + 4*(0x00)))
#define TX_BUF_DATA_DBG 	((u32*) (BRAM_WRITE_BASE_ADDRESS + 4*(0x01)))

#define CLK_DIV_BAUD_UART 	((u32*) (BRAM_WRITE_BASE_ADDRESS + 4*(0x02)))
#define TX_BUF_DATA_UART	((u32*) (BRAM_WRITE_BASE_ADDRESS + 4*(0x03)))

#define CLK_DIV_BAUD_RS232 	((u32*) (BRAM_WRITE_BASE_ADDRESS + 4*(0x04)))
#define TX_BUF_DATA_RS232	((u32*) (BRAM_WRITE_BASE_ADDRESS + 4*(0x05)))

#define CLK_DIV_BAUD_RS422 	((u32*) (BRAM_WRITE_BASE_ADDRESS + 4*(0x06)))
#define TX_BUF_DATA_RS422	((u32*) (BRAM_WRITE_BASE_ADDRESS + 4*(0x07)))




#define RX_BUF_EMPTY_DBG 	((u32*) (BRAM_READ_BASE_ADDRESS + 4*(0x00)))
#define RX_BUF_DATA_DBG 	((u32*) (BRAM_READ_BASE_ADDRESS + 4*(0x01)))
#define TX_BUF_FULL_DBG 	((u32*) (BRAM_READ_BASE_ADDRESS + 4*(0x02)))

#define RX_BUF_EMPTY_UART 	((u32*) (BRAM_READ_BASE_ADDRESS + 4*(0x03)))
#define RX_BUF_DATA_UART 	((u32*) (BRAM_READ_BASE_ADDRESS + 4*(0x04)))
#define TX_BUF_FULL_UART 	((u32*) (BRAM_READ_BASE_ADDRESS + 4*(0x05)))

#define RX_BUF_EMPTY_RS232 	((u32*) (BRAM_READ_BASE_ADDRESS + 4*(0x06)))
#define RX_BUF_DATA_RS232 	((u32*) (BRAM_READ_BASE_ADDRESS + 4*(0x07)))
#define TX_BUF_FULL_RS232 	((u32*) (BRAM_READ_BASE_ADDRESS + 4*(0x08)))

#define RX_BUF_EMPTY_RS422 	((u32*) (BRAM_READ_BASE_ADDRESS + 4*(0x09)))
#define RX_BUF_DATA_RS422 	((u32*) (BRAM_READ_BASE_ADDRESS + 4*(0x0A)))
#define TX_BUF_FULL_RS422 	((u32*) (BRAM_READ_BASE_ADDRESS + 4*(0x0B)))



#endif
